[mypy]
python_version = 3.10
strict = true
show_error_codes = true
pretty = true
files =
  python/packages/core/src,
  python/packages/openai/src,
  python/packages/openai-compatible/src,
  python/packages/deepseek/src,
  python/packages/anthropic/src,
  python/examples
mypy_path =
  python/packages/core/src,
  python/packages/openai/src,
  python/packages/openai-compatible/src,
  python/packages/deepseek/src,
  python/packages/anthropic/src

[mypy-tests.*]
ignore_errors = true
